spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 10000
      connection-timeout: 30000
      max-lifetime: 300000
  aop:
    proxy-target-class: true

  data:
      redis:
        host: localhost   # 또는 Redis 서버 주소
        port: 6379
        database: 0
        timeout: 60000
        connect-timeout: 60000
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: dsalkewqooeowique_dsadiosanmdsanm_djsakldjlksajdlk_duwuwudnksma
